# vim: set ts=2 expandtab!:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet9-deployment
  labels:
    app: planet9
spec:
  replicas: 3
  selector:
    matchLabels:
      app: planet9
  template:
    metadata:
      labels:
        app: planet9
    spec:
      containers:
      - name: planet9
        image: gcr.io/planet9-k8s/planet9:test2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
